version: "3"

services:
 
  sonarqube:
    image: sonarqube:community
    depends_on: # This container is not going to be starter till the db container gets ready
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      # - sonarqube_data:/opt/sonarqube/data
      # - sonarqube_extensions:/opt/sonarqube/extensions
      #- sonarqube_logs:/opt/sonarqube/logs
      - /home/ubuntu/environment/data/sonarqube/data:/opt/sonarqube/data
      - /home/ubuntu/environment/data/sonarqube/extensions:/opt/sonarqube/extensions
      - /home/ubuntu/environment/data/sonarqube/logs:/opt/sonarqube/logs
    ports:
      - "8080:9000"
      
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      #- postgresql:/var/lib/postgresql
      #- postgresql_data:/var/lib/postgresql/data
      - /home/ubuntu/environment/data/postgresql/core:/var/lib/postgresql
      - /home/ubuntu/environment/data/postgresql/data:/var/lib/postgresql/data

#volumes: # NAMED VOLUMES
# We don't like named volumes... for this purpose at least.,..
# I told you we could use volumes for 3 different things:
# - Share data between containers: NAMED VOLUMES
# - Persist information after container deletion
# - Inject files/folders to containers
# Names volumes are the same as regular volumes... but I do not know the actual folder where the data is stored on my host
# I our case we are using volumes to PERSIST DATA... for exmple the DATABASE DATA!!!
# In thiis case we want to be able to know the actual folder on the HOST

# Usually companies provides docker-compose examples using NAMED VOLUMES... WHY?
# Because they don't know the actual folder that could exist on each computer
# They do not know in which folder I want to keep the information
# By using named volumes, this docker file works on EVERY SINGLE COMPUTER
# As a test (proof of concept) is ok
# But not for working on a real scenario.... LETS CHANGE THAT
  #sonarqube_data:
  #sonarqube_extensions:
  #sonarqube_logs:
  #postgresql:
  #postgresql_data:
  
 # docker compose up -d